name: "Deploy to AWS S3"

description: "Deploy a static website via AWS S3"

inputs:
  bucket-name:
    description: "The AWS S3 bucket name"
    required: true
  bucket-region:
    description: "The AWS S3 bucket region"
    required: true
  dist-folder:
    description: "The folder that contains the files that must be deployed"
    required: false
    default: "dist"

outputs:
  app-url:
    description: "The URL of the deployed application"

runs:
  using: "node16"
  main: "main.js"
